name: 'Tests'
on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install dependencies
        uses: cypress-io/github-action@v1
        with:
          runTests: false
      - name: setup node
        uses: actions/setup-node@v1

      - name: install
        run: npm install

      - name: E2E
        uses: cypress-io/github-action@v1
        with:
          start: npm run develop:ci
          install: false
          headless: true
          working-directory: 'client'
          wait-on: 'http://localhost:3000'
