name: 'Tests'
on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1


      - name: Install dependencies
        uses: cypress-io/github-action@v1
        with:
          runTests: false

      - name: setup node
        uses: actions/setup-node@v1
        env:
          NODE_ENV: ${{ secrets.NODE_ENV }}
          DB_CONNECT_ATLAS: ${{ secrets.DB_CONNECT_ATLAS }}
          DB_CONNECT_MLAB: ${{ secrets.DB_CONNECT_MLAB }}
          TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          EXPIRATION_TIME: ${{ secrets.EXPIRATION_TIME }}
      - run: npm install
      - run: npm run heroku-prebuild
      - run: npm run develop:ci -- --silent &
      - run: npm run ci:run
        env:
          CI: true
