name: 'Tests'
on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install dependencies
        uses: cypress-io/github-action@v1
        with:
          runTests: false
      - name: setup node
        uses: actions/setup-node@v1

      - name: install server 
        run: npm install
      - name: install client
        run: heroku-prebuild
      
      - name: Start server in the background
        run: npm run develop:ci

      - name: E2E
        uses: cypress-io/github-action@v1
        with:
          install: false
          headless: true
          working-directory: 'client'
          wait-on: 'http://localhost:3000'
