name: 'Tests'
on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1


      - name: Install dependencies
        uses: cypress-io/github-action@v1
        with:
          runTests: false

      - name: setup node
        uses: actions/setup-node@v1
      - run: npm install
      - run: npm run heroku-prebuild
      - run: npm run develop:ci &
      - run: npm run cy:run
        env:
          CI: true
